version: '3.8'

services:
  esp-idf:
    image: espressif/idf:latest
    container_name: esp32-dev
    working_dir: /project
    volumes:
      - .:/project
      - esp-idf-tools:/root/.espressif
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0  # Adjust based on your ESP32 connection
    command: /bin/bash
    stdin_open: true
    tty: true

volumes:
  esp-idf-tools: